### ISSUE TITLE
漫画更新列表空白，排行榜空白

### ISSUE THREAD

**Issue by UnluckyNinja** [xiaoyaocz/dmzj_flutter#16]
版本1.0.6，今天（4月26）早上发现的问题
漫画更新列表刷新依然空白，使用旧版dmzj app显示“请先升级版本”，猜测可能是web api变动

排行榜这个空白有一段时间了，但看很久都没有人提issue，不知道是不是个别现象

EDIT: 得，27号连漫画都看不了了……

**Comment by Kei-Asai** [comment]
与楼上完全相同的问题，猜测可能需要更新下api

**Comment by AliceRabbit** [comment]
同样的问题，应该是api挂了

**Comment by ShowMeThe** [comment]
新接口改了 ，不是明文， 是加密的  http://nnv4api.dmzj1.com/comic/update/list/100/1

**Comment by UnluckyNinja** [comment]
1.1.1试了下，以上问题都解决了，如果明天大妈之家不针对性更新的话，应该可以close了
顺便佩服一下作者逆向重构效率是真的高😂
