### ISSUE TITLE
1.1.0版本 漫画“更新”中译制漫画为空

### ISSUE THREAD

**Issue by zhongfly** [xiaoyaocz/dmzj_flutter#18]
“更新”中只显示国漫，汉化漫画没有出现，并且选择“译制漫画”，列表完全空白
![Screenshot_20210429165907](https://user-images.githubusercontent.com/11155705/116526720-7a361b00-a90c-11eb-8d7a-d23c56582f9f.png)
ps:1.1.0是我根据您项目源码自己编译的…

**Comment by xiaoyaocz** [comment]
更新1.1.1，登录后可见
