### ISSUE TITLE
打开APP无内容

### ISSUE THREAD

**Issue by stlion** [xiaoyaocz/dmzj_flutter#34]
2021年6月16日打开APP无内容，尝试用浏览器打开dmzj1.com无内容，而dmzj.com则可以，是不是动漫之家改接口了？请检查，谢谢。

**Comment by xiaoyaocz** [comment]
更新至1.2.0
https://github.com/xiaoyaocz/dmzj_flutter/releases

**Comment by stlion** [comment]
> 更新至1.2.0
> https://github.com/xiaoyaocz/dmzj_flutter/releases

更新后问题已解决，太好了～
