### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by ilusrdbb** [xiaoyaocz/dmzj_flutter#69]
是不是api变了
切不切网页api都一样
![Screenshot_2022-09-27-12-38-20-469_com nsapp dmzj](https://user-images.githubusercontent.com/26247398/192433545-7ea8196b-49df-4e82-985b-04d094af96db.jpg)

**Comment by Schezuk** [comment]
`http://nnv3api.muwai.com/chapter/39695/86353.json`似乎失效

`http://v4api.dmzj8.com/comic/chapter/8/17617`是新api

**Comment by Schezuk** [comment]
`https://m.dmzj.com/chapinfo/8/17617.html` 是非protobuf的，可以

`https://api.m.dmzj.com/comic/chapter/53646/101979.html` 不能看隐藏的

**Comment by ilusrdbb** [comment]
无法登陆
![IMG_20220928_195412](https://user-images.githubusercontent.com/26247398/192772462-1f813d01-7ba4-4a61-b313-fe5bbffe81e7.jpg)

**Comment by ilusrdbb** [comment]
更新后好使了
